### ISSUE TITLE
Glaubenspunkte & Glaubensbalken

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#101]
Wird noch editiert...

**Comment by Alter04** [comment]
- [ ] Der Glaubensbalken ist sichtbar, nachdem die erste Opferstätte gebaut wurde.

- [ ] Der Glaubensbalken, soll links oben in der Navigationsleiste dauerhaft sichtbar sein. 

**Glaubensbalken - fortführen Gb. genannt**

- [ ] Der Gb. ist markiert wie eine Zeitleiste und hat einen Positiven und einen Negativen Bereich.

- [ ]  Insgesamt hat der Gb. also eine Vorderseite und eine Rückseite.

- [ ]  Jede Seite ist unterteilt in 10 Fächer, die wie bei einer Zeitleiste, durch Strichmarkierungen unterhalb der Leiste sichtbar sind. 

- [ ]  Jeder Strich zählt für 10 Punkte. So geht der Gb. im Positiven, sowie im negativen Bereich von 0 bis 100, sowie von 0 bis -100. 

**Funktion**
- [ ] Sichtbar in der Navigationsleiste ist der Gb. nur als eine Leiste, welche mit den Unterstrichen markiert ist. Erst mit einem Klick auf die Leiste, welche als Button ebenso funktioniert, öffnet sich ein Fenster. So hat man eine dauerhafte direkte Einsicht auf seinen Glaubensstand, aber kann für Details, den Fenstermodus öffnen. 

**Weitere zusammenhängende Funktionen & Erläuterung**
Der Glaube und die Glaubenspunkte können sich im laufe des Spiels, abhängig von der Spielweise, Geschehnissen, Entscheidungen, sowie Wetterlagen, oder auch Quest's positiv wie auch negativ für den Spieler entwickeln. 
Durch eine abgeschlossene Aufgabe, bekommt der Spieler beispielweise Glaubenspunkte gut geschrieben, sollte er manche Aufgaben ablehnen, oder nicht innerhalb einer bestimmten Zeit erledigen, oder nicht schaffen, so bekommt er Glaubenspunkte abgezogen.
Durch Opfergaben, ausreichende Opferstätten und individueller Entscheidungen im Gefecht, können Glaubenspunkte hinzugewonnen oder verloren gehen.

Die Glaubenspunkte sollen helfen, wenn es um die Ernte geht, oder das im Krieg oder Gefecht unterstützend wirken. - Die Götter sind auf unserer Seite - 

- [ ] Ist der Gb. im positiven Bereich (+0), hat dieser **keinen** negativen Einfluss auf das Spiel.

- [ ] Ist der Gb. im negativen Bereich (unter 0), hat dieser einen **negativen** Einfluss auf das Spiel.

So können beispielweise Krankheiten entstehen, oder geheilt werden. Feuer können schneller entfachen, oder das Wetter kann umschwingen, aber auch Ernten können nicht gut ausfallen.
Diese Punkte werden aber noch später auf den Spieler zu kommen, da sich der Spieler, ersteinmal die Götterwelt aufbauen muss und die Götter kennenlernt.
Im laufe des Spiels und der Zeit, kommen so Hindernisse und Belohnungen hinzu, die dann als Issues hier aufgelistet werden - natürlich mit Funktionalitäten.

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/41874883-79fbf7ac-78c9-11e8-9406-a408b95faad0.png)
