### ISSUE TITLE
Optionen & Tastenkombinationen

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#103]
- [x] Gedrückte Mausrad-Taste und man kann sich drehen ( Bisher glaube ich Q & E ) - Auch die Tastenkombinationen bleiben bestehen, allerdings wird eben die Eigenschaft des Mausrades hinzugefügt.

- [x] Linksklick gedrückt halten - Auswahlrahmen ziehen 

- [x] Taste "M" = Karten-Ansicht zeigen ( mini-map ) 
Dazu kommt noch eine grafische Erklärung, wie diese aussehen soll. 

- [x] Bewohner ausgewählt + drücken taste "B" = bauen - das Baumenü öffnet sich direkt.

- [x] Niemanden ausgewählt - taste "." = abreißen

- [x] Gebäude ausgewählt - Taste "," = drehen

- [x]  Niemanden ausgewählt - Taste "J" = Berufsübersicht

- [x]  Mehrere Bewohner / Objekte / Soldaten etc ausgewählt - "STRG" + eine beliebige Zahl von 0-9 gruppiert diese zusammen. Drückt man als Shortcut dann diese beliebige Zahl, sind alle gruppierten Objekte wieder in der auswahl. 

Besonderheit: Funktioniert nur bei gleichen Gebäuden - soll rekrutierung später vereinfachen, obwohl man woanders auf der karte ist, bzw nicht in der nähe ist. 

Zusatz: doppeltes klicken auf diese beliebige zahl - lässt den bildschirm zur auswahl gleiten.

**Comment by flokicker** [comment]
Das verscheiebn/drehen der Gebäude (ausserhalb des baumodus) funktioniert und deshalb schlage ich vor, dass "," bei dem Gebäude in den verschieben modus wechselt, dann kann man nochmals mit "," drehen

**Comment by flokicker** [comment]
Niemanden ausgewählt - Taste "J" = Berufsübersicht

denke man will auch in die berufsübersicht kommen wenn man jemanden ausgewählt hat, aber hab das mal so gemacht wie du sagst, ist ja schnell geändert

**Comment by flokicker** [comment]
(rausgenommen)
-In der Vogelperspektive - aus der Sicht der Götter, kann man ohne W,S,A,S steuern und navigiert mit der Maus per Links- und Rechtsklick.
- Beim Navigieren der Maus am Bildschirmrand, bewegt sich die Kamera - nicht wie bisher mit W,S,A,D. ABER, man kann auch nur mit der Tastenkombination steuern - es soll beides Möglich sein.

**Comment by flokicker** [comment]
Bis jetzt nur Bewohner gruppierbar, da noch nicht mehrere Gebäude ausgewählt werden können

**Comment by flokicker** [comment]
Probleme mit UI behoben für Mausbewegung am Bildschirm-Rand, implementiert
