### ISSUE TITLE
Kraftort

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#106]
Ein **Kraftort** bzw. **Kraftorte**, sind freie in der Landschaft auffindbare Orte, an denen der Spieler Glaubenspunkte verdienen kann. So kann ein Spieler z.b. einen Sumpf finden, der Göttliche Kräfte besitzt und mit Hilfe eines Priesters, kann der zu einem Kraftort seines Volkes beschworen werden. 

- [x] Der Kraftort ist ein Sammelort für Opfergaben, zu dem die Bewohner pilgern um tote zu beerdigen, oder Güter zu opfern. Ein **Kraftort** ist mit einer leichten weißen Kontur versehen.

- [x] Ein **Kraftort** braucht je nach Größe eine bestimmte Zeit eingenommen zu werden. Für den Start, spielen wir ( wenn Modell vorhanden ) - mit einer Größe. So testen wir das erst einmal. 

- [x] Der Priester arbeitet in dem Gebäude **Opferstätte 1** - pro **Opferstätte 1** kann ein Spieler maximal 1 Priester haben. - Dieser ist, wie oben gesagt, für die Eroberung von Kraftorten zuständig.

- [x] Tempel und Opferstätten sind Gebäude, die je nach Größe und Format Priester als Arbeiter besitzen. Kraftorte hingegen sind Orte, die den Glauben erhöhen und Glaubenspunkte freischalten, allerdings keine Priester beherbergen.

- [x] Kraftorte geben zusätzlich zu den Punkten der **Opferstätte 1** 10 weitere Punkte hinzu. So hat man bei einem Kraftort und einer Opferstätte maximal 20 Glaubenspunkte.
Für jeden weiteren "kleinen" Kraftort, gibt es 5 Glaubenspunkte.

- [x] Die Regeneration ist dadurch nicht beeinflusst. 1 Glaubenspunkt in 5 Minuten.

**Comment by flokicker** [comment]
leuchtet weiss, falls noch nicht eingenommen, blau wenn eingenommen
