### ISSUE TITLE
Technologiebaum - Steinzeit - Konzept

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#107]
- [x] Verwendete Ressourcen um im Technologiebaum zu forschen : Baumaterial, Nahrungsgüter, Tiere, Glaubenspunkte

- [ ] Nachdem man eine Opferstätte gebaut hat, bekommt man die Aufgabe den Tüftler zu bauen. Sobald dieser seine Arbeit aufnimmt erscheint der Technologiebaum-button.

- [x] Solange die Opferstätte nicht gebaut ist, ist der Tüftler im Baumenü nicht sichtbar.

- [x] Sobald er sichtbar ist, blinkt das Baumenü - zwecks neuem zur Verfügung stehendem Gebäude.

- [x] Der Technologiebaum ist senkrecht angelegt und ist für jede Zeit aufgeteilt. So kann er zugeklappt und aufgeklappt werden um die Übersicht zu verbessern im späterem Spielstadium, sowie gestattet das zurück blicken auf alte Technologien um Freunden oder Mitspielern auszuhelfen.

- [x] Der Technologiebaum hat mehrere Äste, die sich wiederum aufteilen können.

Siehe hier:

![technologiebaum](https://user-images.githubusercontent.com/37193587/39725117-14e21aee-524b-11e8-83f3-1225e453beb5.png)

**Comment by flokicker** [comment]
Das Baumenu ist nun ja nichtmehr links, sondern bei den Bewohnern im Menu... wie soll ein neue verfügbares Gebäude sichtbar sein? also blinkt der knopf bei der bewohnerinfo?

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/42238767-3d842652-7f02-11e8-8e05-05bf1254d5c8.png)

**Comment by Alter04** [comment]
Ja genau!

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/42291095-e66ceba6-7fc9-11e8-8189-a0a8ff022606.png)

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/42292016-bd082a36-7fcf-11e8-8f51-fae2efd544cf.png)

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/42294405-d71d435a-7fe0-11e8-90ad-fd5eb188f71b.png)

Baumenu blinkt nun

**Comment by flokicker** [comment]
#120
