### ISSUE TITLE
Held - Kamera Verfolgung

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#109]
Es gibt 2 Perspektiven

- [x] Generelle Steuerung: 
Laufen : w,s,a,d
Drehen links = Q
Drehen rechts = E
Springen = Leertaste
Mausrad oder R gedrückt halten = Rotation um Helden 
rechtklick auf dem Boden = Navigieren / aufheben
Inventar = i
Aufheben = F
Ablegen ( Wild ) = F

- [x] Normaler Modus:
- Der Held soll in einer leichten Vogelperspektive steuerbar und zu verfolgen sein.
( Der Held ist komplett zu sehen. )
- Hier findet die normale Steuerung statt. Der Held läuft, rennt, schleicht, springt und tanzt in dieser Position der Kamera.
- **Tastenkombination X** = Schleichen / Laufen ( 1x drücken = schleichen, 2x drücken = laufen 3x drücken = rennen, 4x drücken = schleichen usw.....)
- Die Waffe ist nicht gezogen

- [x] Kampfmodus: Der Held ist nur von der Schulter an zu sehen. Die Kamera ist näher an dem Helden. Der Held schleicht oder läuft. 
- **Tastenkombination X** = Schleichen / Laufen ( 1x drücken = schleichen, 2x drücken = laufen 3x drücken = schleichen usw.....)
- Ein kleines Fadenkreuz soll das anvisieren der Gegner/Tiere ermöglichen. ( Bsp bei Pfeil und Bogen )
- Die Waffe ist nur im Kampfmodus gezogen.

**Comment by flokicker** [comment]
aufheben und ablegen kommt später
