### ISSUE TITLE
Menschen Lebenszyklus

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#116]
Um das Spiel realistisch darzustellen, brauchen die Menschen einen festen Zyklus.
Dieser soll mit Entwicklung und Technologie verbessert werden können.
So sollen durch erfolgreiches Spiel, die Menschen älter werden, gesünder werden und so auch auf Dauer das Volk größer werden.

- [x] Mindestens 1 Mann und 1 Frau können Kinder kriegen, ohne Mann oder Frau (innerhalb des Bau-Bereichs wo die Wohnungen sind), ist es nicht möglich Kinder zu bekommen. 
- [x] Frauen sollen schwanger werden und so vergeht 9 Monate (ingame-Zeitrechung) bis das Kind geboren wird. 
- [x] Ist kein Mann oder keine Frau mehr vorhanden, ist eine neue Schwangerschaft und somit neue Kinder - nicht möglich.
- [x] Durch Quest oder Gebietserkundungen, können aber neue Personen ausfindig gemacht werden, um das Volk auf der einen Seite zu vergrößern und zu retten in einer Phase der schlechten Wirtschaft
- [x] Sobald die Kinder geboren werden, spielen diese in den ersten 12 Lebensjahren umher. Man kann sie anklicken, doch sie bewegen sich automatisch umher. Sie sind nicht zu navigieren. 
- [x] Ab ihrem 12 Lebensjahr bis ins 16 Lebensjahr, helfen sie der Mutter und tätigen die selben arbeiten. ( Beeren/Korn/Pilz sammeln, kochen, feuerholz nachlegen, Fell herstellen ) 
- [x] Sie begleiten die Mutter, somit laufen sie von A nach B nur wenn die Mutter läuft. Ebenso sammeln sie die Pilze/Beeren etc nur dann, wenn die Mutter das macht.
Ebenso legen sie nur dann die Ressourcen ab, wenn die Mutter es tut.
Ist die Mutter untätig, spielen die Kinder - auch mit anderen zusammen. ( je nach animationen dann später :D )
- [x] Ab 16 Jahren kann man die Kinder navigieren
- [x] ab 18 Jahren, können sie Kinder kriegen
- [x] In der Steinzeit leben sie 45-55 Jahre

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/42474989-92573acc-83c9-11e8-8b43-0753b3f57bc7.png)

Frauen können nun schwanger werden

**Comment by flokicker** [comment]
Da ist noch ein wichtiger (und riesiger :D) punkt dabei:

"Durch Quest oder Gebietserkundungen, können aber neue Personen ausfindig gemacht werden, um das Volk auf der einen Seite zu vergrößern und zu retten in einer Phase der schlechten Wirtschaft"

Dass es "wilde" Bewohner geben soll, die (vorerst) irgendwo auf der Map herumlaufen und man kontrollieren kann, sobald man sie mit einem Männchen anspricht oder so?
