### ISSUE TITLE
Cheats - Chatfensternutzung

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#117]
Im Chatfenster per " / " + Befehl gibt man die Befehle ein.

Karte Sichtbar = /Openmap
Karte wieder unsichtbar machen ( auf das was man erforscht hat zurückstellen ) = /Closemap
Zeit einblenden (Jahreszeit + Monat ) = /Openyear
Zeit ausblenden = /closeyear
Spielgeschwindigkeit Normalisieren ( 1x Speed ) = /Speedone 
Spielgeschwindigkeit erhöhen ( 2x Speed ) = /Speedtwo 
Spielgeschwindigkeit erhöhen ( 3x Speed ) = /Speedthree

Ressourcen direkt ins Lager:
1000 Holz = /Wood
1000 Stein = /stone
1000 Fisch = /steak
1000 Korn = /corn

Bewohner spawnen = /bornbaby

**Comment by flokicker** [comment]
Habs einwenig abgeändert, dass es flexibler ist

Spielgeschwindigkeit verändern = /speed [faktor]

Jahre vergehen lassen = /years [jahre]

Ressourcen an ausgewählte Person = /give [resNr] [anzahl]
0=Holz ,1=Stein ,2=Eisen ,3=Bronze ,4=Silber ,5=Pilz ,6=Fisch ,7=Fleisch ,8=Korn ,9=Roher Fisch ,10=Knochen ,11=Fell ,12=Knochen-Werkzeug ,13=Keule ,14=Tote Ente ,15=Wildzahn ,16=Halskette

Bewohner spawnen = /bornbaby

**Comment by Alter04** [comment]
mach mal noch /bornman und /bornwoman

**Comment by flokicker** [comment]
mach ich ^^

hab noch /tcost eingeführt, macht dass die gebäude direkt gebaut werden ohne kosten

**Comment by Alter04** [comment]
Ah top.

Kannst du auch einrichten, das wenn wir "ü" gedrückt halten, alle cheats in einer liste angezeigt werden? :)

**Comment by flokicker** [comment]
hab einen /help command gemacht, noch ein UI-Fenster mehr ist mühsam für den Moment

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/42584194-ebb7655a-8532-11e8-9613-b6b402e2e04d.png)

**Comment by Alter04** [comment]
ja oder so, das ist ja ausreichend. passt!

**Comment by flokicker** [comment]
ich close den issue mal, alle befehle funktionieren soweit :D
