### ISSUE TITLE
Quests / Aufgaben

### ISSUE THREAD

**Issue by flokicker** [flokicker/dorfbauprojekt#120]
- Ausarbeitung von wenigen Quests zum testen
- UI-Design
- Implementieren in Spielablauf

"Nachdem man eine Opferstätte gebaut hat, bekommt man die Aufgabe den Tüftler zu bauen. Sobald dieser seine Arbeit aufnimmt erscheint der Technologiebaum-button." #107 
"Durch Quest oder Gebietserkundungen, können aber neue Personen ausfindig gemacht werden, um das Volk auf der einen Seite zu vergrößern und zu retten in einer Phase der schlechten Wirtschaft" #116

**Comment by Alter04** [comment]
Willst du ne kleine Quest Liste haben die ich erstelle, oder machst du das selbst ?
