### ISSUE TITLE
Quest

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#123]
ein paar beispiel quest die natürlich keine storyline haben... das kommt dann ab 1.4 

- [x] Sammel X Holz ( die anzahl die für den bau benötigt wird ) 
+ Baue 1 Unterschlupf 

- [x] Erkunde die Gegend und finde Wasser 
+ Baue 1 Fischer 
+ und fange 25 Fisch

- [x] Sammel 25 Pilz

- [x] Baue 1 Tüftler

- [x] Erschaffe einen Priester 
+ finde einen Kraftort 
+ schalte ihn frei

**Comment by Alter04** [comment]
die punkte unter einer quest dienen als extra zusatz und die gesamte quest ist erst dann abgeschlossen, wenn alle teile der quest abgeschlossen sind.

- ein teil der quest / ein punkt = teilabschnitt der Quest

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/43366907-f72bc8a2-9344-11e8-9da4-87e3ef49efc1.png)

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/43367064-86bf9e38-9347-11e8-899c-f5258eaae9a4.png)
