### ISSUE TITLE
Erfolge

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#124]
- [x] **Erfolge ( keine Quest ) sollen dauerhafte Errungenschaften festhalten und als nettes Extra dienen.**

- [x] Die Quest sollen im Profil-Fenster zu sehen sein, damit man sie jeder Zeit einsehen kann, an welchen Erfolgen man arbeiten kann, damit man diese erfüllt. Sie bringen aber keine Belohnung.

- [x] Hat man einen Erfolg eingelöst, steht in kursiv und in 70% Deckkraft darunter das nächste lvl um zu sehen, was man für die nächste Stufe braucht. 

- [x] Anstelle von Lvl wird im Spiel "Stufe" geschrieben

Erfolgtitel - **Der Holzfäller**:
- [x] Holfäller lvl 1 - 50 Holz gesammelt
- [x] Holzfäller lvl 2 - 250 Holz gesammelt 
- [x] Holzfäller lvl 3 - 1.000 Holz gesammelt
- [x] Holzfäller lvl 4 - 2.500 Holz gesammelt
- [x] Holzfäller lvl 5 - 5.000 Holz gesammelt
- [x] Holzfäller lvl 6 - 10.000 Holz gesammelt
- [x] Holzfäller lvl 7 - 25.000 Holz gesammelt
- [x] Holzfäller lvl 8 - 50.000 Holz gesammelt
- [x] Holzfäller lvl 9 - 100.000 Holz gesammelt
- [x] Holzfäller lvl 5 - 1.000.000 Holz gesammelt

Erfolgtitel - **Der Fischer**:
- [x] Fischer lvl 1 - 50 Fisch gesammelt
- [x] Fischer lvl 2 - 250 Fisch gesammelt 
- [x] Fischer lvl 3 - 1.000 Fisch gesammelt
- [x] Fischer lvl 4 - 2.500 Fisch gesammelt
- [x] Fischer lvl 5 - 5.000 Fisch gesammelt
- [x] Fischer lvl 6 - 10.000 Fisch gesammelt
- [x] Fischer lvl 7 - 25.000 Fisch gesammelt
- [x] Fischer lvl 8 - 50.000 Fisch gesammelt
- [x] Fischer lvl 9 - 100.000 Fisch gesammelt
- [x] Fischer lvl 5 - 1.000.000 Fisch gesammelt

Erfolgtitel - **Der Bergarbeiter**:
- [x] Bergarbeiter lvl 1 - 500 Stein gesammelt 
- [x] Bergarbeiter lvl 2 - 2.500 Stein gesammelt
- [x] Bergarbeiter lvl 3 - 5.000 Stein gesammelt
- [x] Bergarbeiter lvl 4 - 25.000 Stein gesammelt
- [x] Bergarbeiter lvl 5 - 50.000 Stein gesammelt
- [x] Bergarbeiter lvl 6 - 100.000 Stein gesammelt
- [x] Bergarbeiter lvl 7 - 250.000 Stein gesammelt
- [x] Bergarbeiter lvl 8 - 1.000.000 Stein gesammelt
- [x] Bergarbeiter lvl 9 - 10.000.000 Stein gesammelt
- [x] Bergarbeiter lvl 10 - 25.000.000 Stein gesammelt

Erfolgtitel - **Zivilisation**:
- [x] Stufe 1 - 10 Bewohner
- [x] Stufe 2 - 25 Bewohner
- [x] Stufe 3 - 50 Bewohner
- [x] Stufe 4 - 100 Bewohner
- [x] Stufe 5 - 200 Bewohner
- [x]  Stufe 6 - 500 Bewohner
- [x] Stufe 7 - 750 Bewohner
- [x] Stufe 8 - 1.000 Bewohner
- [x] Stufe 9 - 1.500 Bewohner
- [x] Stufe 10 - 2.500 Bewohner

Erfolgstitel - **Sensenmann** (Soldaten nicht hier aufgezählt )
- [x] Stufe 1 - Gestorbener Bewohner - 1
- [x] Stufe 2 - Gestorbener Bewohner - 5
- [x] Stufe 3 - Gestorbener Bewohner - 25
- [x] Stufe 4 - Gestorbener Bewohner - 50
- [x] Stufe 5 - Gestorbener Bewohner - 100
- [x] Stufe 6 - Gestorbener Bewohner - 250
- [x] Stufe 7 - Gestorbener Bewohner - 500
- [x] Stufe 8 - Gestorbener Bewohner - 1.000
- [x] Stufe 9 - Gestorbener Bewohner - 1.500
- [x] Stufe 10 - Gestorbener Bewohner - 2.500

Erfolgstitel - **Glauben**
- [x] Stufe 1 - Beschäftige Priester - 1
- [x] Stufe 1 - Beschäftige Priester - 3
- [x] Stufe 1 - Beschäftige Priester - 10
- [x] Stufe 1 - Beschäftige Priester - 25
- [x] Stufe 1 - Beschäftige Priester - 50

Erfolgstitel - **Bauherr** ( nur Unterschlupf/Häuser)
- [x] Stufe 1 - Baue Unterschlupf - 1
- [x] Stufe 2 - Baue Unterschlupf - 3
- [x] Stufe 3 - Baue Unterschlupf - 5
- [x] Stufe 4 - Baue Unterschlupf - 25
- [x] Stufe 5 - Baue Unterschlupf - 50

Erfolgstitel - **Valhalla** ( nur soldaten )
- [x] Stufe 1 - Toter Krieger - 1
- [x] Stufe 2 - Toter Krieger - 10
- [x] Stufe 3 - Toter Krieger - 25
- [x] Stufe 4 - Toter Krieger - 50
- [x] Stufe 5 - Toter Krieger - 100

**Comment by Alter04** [comment]
das sieht schon mal cool aus ! :)

**Comment by flokicker** [comment]
siehe #126
