### ISSUE TITLE
Profil Fenster

### ISSUE THREAD

**Issue by flokicker** [flokicker/dorfbauprojekt#126]
- Wo kommt das Fenster hin?
- Wie sieht die Benutzeroberfläche aus?
- Wird das Profil für jeden Spielstand separat gespeichert oder für jeden Spieler?
- Inhalt > Erfolge (#124), etc.

**Comment by Alter04** [comment]
1 Im Profil Fenster - steht das nicht in der Issue? - dachte ich jedenfalls :D 

2 Das machen wir wenn wir generell die Benutzeroberfläche gestalten - bis dato soll einfach ein button im profil die erfolge aufrufen, alternativ überleg ich mir noch was wo wir die erfolge verbuchen. - evt gemeinsam mit den quest in ein fenster.

3. naja, logischerweise denk ich immer für jeden spieler seperat pro spielstand !?

**Comment by Alter04** [comment]
noch offene fragen?

**Comment by flokicker** [comment]
hmm hast du noch ne skizze irgendwo?

**Comment by Alter04** [comment]
Close - Aktuell kein Profilfenster geplant
