### ISSUE TITLE
Bugs und Mini-Updates

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#137]
- [x] Chatfenster plöppt auf, sobald ein bewohner etwas aufnimmt. 
ändern dazu, das man keine nachricht darüber bekommt, es einfach passiert.

- [x] rechtsklick auf den Boden: **Navigieren der bewohner**
Man sieht nicht, ob der bewohner den Befehl annimmt. 
Ändern zu: Befiehlt man einem Bewohner zu punkt B zu laufen, erscheint beim klicken ein grüner punkt auf dem boden. bedient man 2 bewohner, erscheinen im abstand der bewohner voneinander ebenfalls diese punkte. Sprich, da wo der Weg des Bewohners endet, erscheint beim klick ein punkt auf dem boden. So kann man nachvollziehen, das der bewohner den befehl angenommen hat und man kann den weg, bzw das ziel visualisiert nachvollziehen.

- [x] Baufenster eines Gebäudes:
Anstatt die Ressourcen in der Baustelle zu zeigen, sollten diese im Infofenster angezeigt werden.
Ist man weiter rausgezoomt, kann man nicht erkennen wie viele ressourcen noch fehlen. 
So muss man mühsam rein und rauszoomen.
Ändern zu: im Infofenster des Gebäudes anzeigen, welche Ressourcen noch fehlen um den Bau fertig zu stellen. 
Quasi so, wie in der Baustelle ersichtlich -> dann im infofenster

- [x] Einlagerungen automatisieren. 
Holzfäller laufen automatisch vom baum zu lager hin und her und bauen weiter automatisch holz ab.  Genau das selbe beim Pilzstumpf. 
Ist ein Pilzstumpf gefunden, wird dieser automatisch abgebaut. 
Sobald das inventar voll ist, läuft der bewohner los und bringt dies ins Lager/höhle/etc und kommt wieder, bist die pilze verbraucht sind. 

( zum verständnis  - Beim jäger und sammler geht es nicht darum, das einzelne bewohner "sammler" und andere "jäger" sind um für sich selbst zu sorgen - die Gemeinschaft stand im vordergrund. Das versorgen aller war das wichtigste im Leben und im Tagesrythmus. 
So bringen die Leute ihre gefundenen/geernteten/erarbeiteten Ressourcen automatisch in die Gemeinschaft und der Spieler kann entscheiden was damit passiert. )
( außer bei herumliegenden einzelnen hölzern und steinen, diese sollen in der Gegend umherliegen und im laufe des Spiels an bedeutung verlieren.)

- [x] Bug - Mehrere Bewohner sollen an dem selben Baum hacken können. So sollen Bäume aus dem direkten Lager/Dorf schneller entfernt und abgebaut werden. Die Ressourcenbeschaffung wäre extrem mühsam wenn später 10 holzfäller an je verschiedenen bäumen hacken.

- [x] Bewohner hängt im Wasser/kante fest - BUG

- [x] einbauen von Bewohner teleport

**Comment by Alter04** [comment]
**bewohner auf gebäude/baustelle:**
Der Bewohner der sich in/auf einem Gebäude/Baustelle befindet, ist nicht direkt anklickbar.
Man muss aufwändig ein kästchen ziehen um den bewohner aus dem haus zu fischen. 
Bitte abändern, das man wenn man auf den bewohner klicken will - dieser primär ausgewählt wird und erst sekundär das gebäude.

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/45456212-2f7b1c80-b6ea-11e8-8d9b-f420d3436e75.png)

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/45457203-2d1ac180-b6ee-11e8-9988-0e84ee514c13.png)

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/45458572-8be33980-b6f4-11e8-94b5-24d3ae422ac0.png)

nur eine Zeile steht im Chat -> nervt nicht so sehr wie jetzt

**Comment by flokicker** [comment]
Drücke o um Cheats anzuschalten
Dann teleportieren sich die Bewohner wenn du sie irgendwo hin befiehlst :)
