### ISSUE TITLE
Kornfeld stufe 1 

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#140]
kriegst du das programmiert, das in der ersten stufe 5 Kornpflanzen wachsen?

Die Bauern brauchen auf dem Feld 2 Minuten für die aussaht. 
dann passiert 1 minute nichts
dann wachsen die Pflanzen nach einander langsam über 5 Minuten und ab dann kann die ernste beginnen.
sobald das inventar voll ist, bringen sie die körner ins haus, bzw an den angebauten lagerraum.

5 kornpflanzen wachsen
jede kornpflanze gibt 30 Körner

nachdem sie geerntet wurden, braucht der bauer 5 minuten bis alles wieder für eine neue bestellung bereit ist.
 
zusammengefasst 8 minuten bis erntebereit
5 minuten pause und von vorn.

dabei kann sich der bewohner gerne bewegen und über das feld hin und her laufen, als wenn er ( auch ohne animation ) arbeitet.

**Comment by flokicker** [comment]
jepp ist machbar

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/45983317-680ce580-c05c-11e8-978c-5bf93c12a8ed.png)

**Comment by flokicker** [comment]
Alles implementiert bis auf das hin und herlaufen während dem aussähen / ernten, was ich für den Moment auch nicht als wichtig betrachte
