### ISSUE TITLE
Bugs und Feedback zu v0.1.4.4

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#144]
- [x] Pilze ( am baumstamm ) wachsen nicht nach. 

- [x] Pilzstrunk verschwindet nicht wenn er komplett abgearbeitet ist.

- [x] Anzeige fehlt, über Info der im Haus lebenden Bewohner

- [x] Bevölkerungslimit ( 2/10 ) einfügen

- [x] Baustelle direkt versorgen. Bisher: Bewohner nimmt auftrag an, geht zur Baustelle ohne Ressourcen, geht dann zur Höhle/Hütte und besorgt Material - liefert sie dann zur Baustelle.

- [x] Info zu Kindern - Alter fehlt im Info-Fenster

- [x] Alter der erwachsenen Bewohner fehlt ebenso

- [x] Kornfeld Lebensdauer einfügen: Ein Kornfeld hat ab jetzt eine Lebensdauer von 5 Minuten. in den nächsten 2 Minutn verrottet das sich noch auf dem Feld befindende Korn langsam, dannach wird automatisch der Zyklus wiederholt.

- [x] Korn aufnehmen 5x so langsam + genauso langsam in die Hütte legen ( schon erledigt worden glaub ich )

- [x] Bug: Feld kann man nicht verschieben.

- [x] Bug: Bewohner kann nicht von Hinten und von Links nicht in die Hütte. Nur von rechts, oder von Vorne.

- [x] Schwangerschaft veränderung  - 5 Minuten schwanger - 10 minuten bis erwachsen werden

- [x] Fisch Feld - keine Infos über die Fische, wie viele gefangen werden können bzw info über die Anzahl der Fische im Feld fehlt.

**Comment by flokicker** [comment]
Wohnraum bereits bei Baustelle zur Verfügung (sollte nicht sein)

**Comment by flokicker** [comment]
Ressourcenleiste verbugt

**Comment by flokicker** [comment]
Spiel speichern wird Teils neu überarbeitet (Spieler+Aufgaben), dann schau ich ob das speichern besser funktioniert (momentan hab ich keine Probleme)
"Bug: Bewohner kann nicht von Hinten und von Links nicht in die Hütte. Nur von rechts, oder von Vorne." ist mir nie mehr passiert

**Comment by Alter04** [comment]
Wenn es dir nicht passiert ist, setz mal ein Haken dran, ich hatte es ein zwei mal in 1.4.4, aber in 1.4.6 nicht mehr. 

Kommt es wieder vor, mach cih ein video davon und schick es dir.
