### ISSUE TITLE
Bugs und Feedback zu v0.1.4.6

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#145]
- [x] Spiel stürtzt manchmal ab
- [x] manchmal gehen speicherstände bei Spielabsturz verloren / manchmal speichert er beim absturz nicht.
- [x] Holz hacken geräusch um 80% reduzieren
- [x] Nacht 3 Minuten
- [x] Tag 12 Minuten
- [x] Übergang von Tag zu Nacht und von Nacht zu Tag verlängern. 
Untergang = 30 Sekunden 
Aufgang = 25 Sekunden
- [x] Lagerfeuer leuchtet aktuell nicht ( liegt evtl an Grafikeinstellung, ist aber zu Spielwichtig, als das es bei geringer Grafikeinstellung zu schlechter Sichtqualität durchs feuer kommt.)
Sollte das Feuer in geringer Grafikeinstellung kaum/schlecht leuchten ( sinn und zweck ) - die Nacht abschalten bei geringer Grafikeinstellung, da man Nachts kaum was sieht ohne die Feuer.
- [x] Lagerfunktion stimmt nicht überein mit den geplanten Einstellungen.
Es fungiert teils nur die Höhle bzw die größt ausgebaute Hütte. Steinmetz beispielweise lagert nichts selbst ein. Holzlager zählen aktuell in den Hütten nicht zusammen. 
Am besten direkt so lösen, wie ursprünglich gedacht. #130 
**Hinweis** In der Fischerhütte wird NUR Fisch gelagert
Im Holzfäller NUR Holz
Im Steinmetz NUR Stein
Im Bauernhaus NUR Korn & Brot ( jeweils 50 Lagerplatz + 50 Erhöhung pro Stufe )
In der Jagdhütte nur Fleisch, Wildfleisch & Knochen ( jeweils 50 Lagerplatz + 50 Erhöhung pro Stufe )
- [x] Im Winter beim Feld: Info fehlt "Im Winter wächst hier kein Korn"

- [x] **Bug**: Neues Spiel - Namen geben = Nach dem Start haben beide Start-Bewohner den Namen den man zuvor eingegeben hat. 
- [x] **Bug**: Fischgründe übereinander baubar - ändern zu: können nicht überschneiden und man kann so nicht an der selben Stelle einen weiteren Fischgrund anbauen.
- [x] **Bug**: Bei mir im Spiel wurden die ersten 6 kinder geboren, alles Männer.
- [x] **Bug**: Manchmal Blackscreen ingame, bei zu höher Qualitätseinstellung, nur UI im Spiel sichtbar, sowie die Bewohnersillouetten, aber nicht spielbar.

**Comment by flokicker** [comment]
Wenn das Spiel crasht, schau bevor du es wieder neu startest in den Log (sonst wird der überschrieben):
C:\Users\Florian\AppData\LocalLow\DefaultCompany\DorfbauProjekt\output_log.txt
Bie mir ist er daa, du musst halt Florian durch deinen benutzernamen des computers ersetzen

Aufm mac sollte das log file da sein:
~/Library/Logs/Unity/Player.log
