### ISSUE TITLE
Gebäude Information

### ISSUE THREAD

**Issue by flokicker** [flokicker/dorfbauprojekt#20]
Wenn auf ein Gebäude geklickt wird, erscheint ein Infofenster zum Gebäude, dieses muss verbessert/angepasst werden
- Kamerakontrolle?
- **Bug**: Kamera springt an falsche Stelle auf Karte

[Screenshot](https://prnt.sc/ivcxzi)

**Comment by Alter04** [comment]
Welche Information - Bitte Screen hinterlegen
