### ISSUE TITLE
Flora Wachstum

### ISSUE THREAD

**Issue by flokicker** [flokicker/dorfbauprojekt#22]
Neue Bäume wachsen mit einem Faktor, der momentan noch konstant ist

EDIT: allgemeines Flora Wachstum wird implementiert

**Comment by Alter04** [comment]
Kannst du oben Editieren, wie dieser Faktor aussieht, oder ist das aktuell einfach als Wert 1 zu sehen?
Ich würde je nach Monat/Jahreszeit den Faktor abändern.
Ebenso, für Wettereinbrüche ( heiße Sommer / kalte Winter )

**Comment by flokicker** [comment]
Sobald ich den eingebaut habe, kann ich den verändern. Muss aber zuerst dafür sorgen, dass überhaupt Bäume wachsen xD

**Comment by Alter04** [comment]
Schon getan?

**Comment by flokicker** [comment]
nee hab das noch nicht gemacht.. wo siehst du dass es als " done" markiert ist?

**Comment by Alter04** [comment]
Mh, war jedenfalls so. Jetzt seh ich es auch wieder normal. Keine Ahnung - Sorry!

**Comment by flokicker** [comment]
NatureManager behandelt alle Natur bezogenen Sachen
Bis jetzt z.b. Florawachstum
