### ISSUE TITLE
Flora für v1.0

### ISSUE THREAD

**Issue by flokicker** [flokicker/dorfbauprojekt#24]
Modell hinzufügen, anklickbar, abbaubar
- [x]  Pilz
- [x]  Schilf
- [x]  Korn
- [x]  Fels

**Comment by Alter04** [comment]
Bei meiner Version ist der Pilz noch in der Beschreibung Holz, lässt sich aber als Nahrung in den Speicher lagern und bringt bewohner dazu sich zu vermehren. 
Guck mal, ob du nur das Informationsfenster anpassen musst.
