### ISSUE TITLE
Auswahl-Fenster 

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#32]
Die Darstellung des Auswahl-Fensters ( Linksklick auf die Karte zur Auswahl ) funktioniert nicht richtig.

An der Stelle an der man zuletzt geklickt hat, erscheint der weiße Rahmen des Auswahl-Fensters & flackert zusätzlich an der Stelle, an der man begonnen hat die Auswahl zu tätigen.

**Comment by flokicker** [comment]
SUPER Beschreibung des Problems! Das hat mir gleich geholfen den Fehler zu finden!
