### ISSUE TITLE
Typo für Menu

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#33]
Als Typo für unser Menü kann uns vorerst **Arial** dienen
**Arial** wird in unserem Menu mit 80% bis 90% Transparenz angezeigt.
Die Verschiedenen Punkte, sollen linksbündig geordnet werden.
Ist der Cursor über einem Punkt, wird die Transparenz auf 100% gestellt.
Verlässt der Cursor wieder den Punkt verblasst diese wieder.

**Comment by flokicker** [comment]
erste Testversion des Hauptmenus erledigt

![grafik](https://user-images.githubusercontent.com/2488481/39786168-8268532e-531f-11e8-8044-88db82de7ec9.png)
