### ISSUE TITLE
Kartenrand - Steuerung Problem

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#38]
Sobald du dich im Spiel in Richtung des Kartenrandes bewegst, kommst du irgendwann zu der Fläche, an der die Karte zu ende ist. 

Bis dahin, gelangst du mit Hilfe der Maussteuerung bzw w,s,a,d zurück zu deinem Dorf.

Bewegst du dich allerdings darüber hinaus, kommst du nicht zurück zu der Karte.

Lösung: Ein "Ende" der Karte einstellen, damit man nicht darüber hinaus Steuern kann und gar nicht in die Lage kommt.
Sprich, wie einen Würfel, in dem man von innen vor eine unsichtbaren Wand, stehen bleibt.

**Comment by flokicker** [comment]
wird gemacht!

**Comment by flokicker** [comment]
fixed
