### ISSUE TITLE
Bauen - Button 

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#39]
Wenn ein Bewohner angeklickt wird, soll künftig das Bauen - Menu im Fenster des Bewohners angezeigt werden.
So soll ein Bewohner direkt das Bauen beginnen, für das er die Aufgabe bekommen hat. 

Problem bisher: 
-> Menü öffnen
-> Gebäude bauen 
-> Bewohner suchen
-> Zum Bauen befehlen

Lösung:
-> Bewohner anklicken 
-> Baumenü öffnen ( aktiviert Befehl bauen im Hintergrund für diesen Bewohner )
-> Gebäude auswählen und platzieren

**Comment by flokicker** [comment]
Aber der bisherige Bau-Knopf bleibt bestehen? Weil manchmal will man schon den Platz reservieren für das Gebäude und hat vlcht keinen Bewohner in der Nähe

**Comment by Alter04** [comment]
Der Bauknopf ist dann im Bewohner zu finden.
Sprich selbst wenn man mit einem Holzfäller bauen will, er aber erstmal weiter holzen soll, kann man ja das Gebäude platzieren, ihn aber weiter hacken lassen.
Jedenfalls würde ich das ganze so mal gerne in einer Version testen.

**Comment by flokicker** [comment]
Okeii!
