### ISSUE TITLE
Kontur Bewohner

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#41]
Keine Kontur der Bewohner im Spiel ( dauerhaft ), sondern nur dann, wenn sie sich hinter Objekten bewegen ( Gebäude, Bäume, Felsen, etc )

**Comment by flokicker** [comment]
Die Kontur ist nur da, wenn der Bewohner ausgewählt ist.
Wenn du das nicht so willst, brauchen wir einen Vorschlag, wie man sonst erkennen soll, dass er ausgewählt ist.

**Comment by Alter04** [comment]
ok, das lassen wir so.
Wenn Bewohner nicht ausgewählt sind, benötigen sie aber eine "leichte" Kontur, wenn sie hinter Objekten her gehen.

Für den "Auswahl" - Modus ( aktuelle Kontur ) mache ich nachträglich, mit einem Bild, einen Vorschlag.

**Comment by flokicker** [comment]
Ja find ich gut. Das mit der Kontur für die Auswahl muss auch nicht definitiv sein, denke da gibts schönere Varianten.

Um die leichte Kontur hinter Objekten kümmere ich mich.

**Comment by Alter04** [comment]
Supi danke.

Wenn das drin ist, kann man das erstmal so lassen :) 👍

**Comment by flokicker** [comment]
Da sprichst du noch einen guten Punkt an, die Bewohner findet man teilweise ziemlich schlecht. Weiss nicht wie gut das behoben wird mit der Kontur wenn sie hinter Objekten stehen, aber ich hab schon oft gespielt und dann meine Bewohner nicht mehr gefunden xD dann musst eich ganz rauszoomen und die ganze karte auswählen, damit ich sie irgendwo markiert sehen konnte ^^

**Comment by Alter04** [comment]
genau, verpasse den einfach eine Kontur für den Moment, wenn sie sich hinter Bäumen befinden.
Dann dürfte das erstmal "behoben" sein denk ich.

Bestimmt werden wir daran so oder so noch jede Menge feilen.

**Comment by flokicker** [comment]
![grafik](https://user-images.githubusercontent.com/2488481/41875782-3f7d5c3a-78cc-11e8-9778-c05b9b56b497.png)
