### ISSUE TITLE
Holz-Transport

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#42]
Wenn ein Holzfäller holz hackt und den Befehl bekommt, das im Inventar befindene Holz zur Baustelle zu bringen, lädt er dieses ab. Der darauf folgende Befehl ( nördlich des Bewohners ) zu navigieren, funktioniert nicht.
Südlich, östlich und westlich des Bewohners funktioniert.
Auch funktioniert nicht, Holz ( nördlich ) zu hacken.
Südlich, östlich und westlich, funktioniert es.

Ebenso lädt der Bewohner aus dem Lager kein Holz mehr ins Inventar. 

Auch alle anderen Bewohner, tätigen nördlich von ihnen keine Tätigkeiten mehr aus ( holz hacken )

**Comment by flokicker** [comment]
das ist sehr speziell weil nördlich bedeutet gar nichts (du kannst die Kamera drehen mit E und Q)

Ich hab keinen Blassen wo nördlich ist bzw. was das Problem sein könnte.
kannst du das evtl mal filmen / screenshoten? wenn ich das problem im editor nicht reproduzieren kann, habe ich keine chance es zu beheben

**Comment by Alter04** [comment]
Ok, klar.
Dann film ich das mal ab und stell es hier rein. 
Hast du ein tool, zum filmen ?
Lightshot bräuchte das mit direct-upload :D

**Comment by flokicker** [comment]
hmm ist mühsam den bildschirm mit einem programm aufzunehmen, die meisten kosten (kenn grad keins dass das gratis macht (und auch grad keins das kostet lol aber kannst mal googlen)) oder du machst das kurz mit dem handy, die qualität überleb ich schon. Muss nur grob sehen wo du hinklickst etc.

**Comment by Alter04** [comment]
ok top
