### ISSUE TITLE
Beruf - Verbesserung

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#43]
Umbenennen von "Job" zu "Beruf"

Zu finden im Fenster der Bewohner, wenn dieser ausgewählt ist. ( Rechts unten )

**Comment by flokicker** [comment]
Überreste vom Englischen ;)
Die Variablen im Programm sind alle auf Englisch, da heissts eben Job. 
Wird in 0, nichts erledigt

**Comment by flokicker** [comment]
![Screenshot der Anpassung](https://user-images.githubusercontent.com/2488481/37880945-9365a700-3090-11e8-8056-d6805e90f06e.png)

**Comment by Alter04** [comment]
Dachte ich mir schon mit dem Englischen, danke! :)
