### ISSUE TITLE
Fenster - Gebäude

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#45]
klickt man ein gebautes Gebäude an, springt das Spiel immer zu einer Stell im Osten der Karte, egal wo sich das Gebäude befindet.

Beim Öffnen der Gebäudeinformation, soll sich die Karte nicht weg bewegen, sondern auf der Stelle bleiben, an der man sich aktuell befindet.

**Comment by flokicker** [comment]
den Issue hab ich schon gestellt, wird geschlossen
#20

**Comment by Alter04** [comment]
Oh, sorry, übersehen!

**Comment by flokicker** [comment]
kein ding ;)
