### ISSUE TITLE
Pilz Gesamtpaket

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#65]
In der Dropbox hinzugefügt Pilz_Gesamtpaket.blend

Bitte die erste Seite aus dem Paket hinzufügen und durch die bisherigen Pilze ersetzen.

Allerdings, wachsen diese Pilz-Fundorte nicht mehr, sondern werden im Leveldesign platziert und müssen so gefunden werden. Einmal weg - muss man sich neue suchen. 
Im Laufe der Zeit, soll es so zwei unterschiedliche Pilze geben.
Welche die nach wachsen, sowie Pilze die als Luxus zählen ( später, vor erst aber nur einen zum Nahrungszweck )

Die erste Seite im Gesamtpaket beinhaltet 35 kg Pilz.

Die Flora für Pilze aber nicht abschaffen, es sollen auch einzelne gefunden werden könenn.
Allerdings den Wachstum um das 10 fache reduzieren. ( zum test )

**Comment by flokicker** [comment]
Ich denke 35 ist etwas zu viel, allerdings hab ich das mal so gelassen!

Für den Moment sind alle Pilze gleich
