### ISSUE TITLE
Gebäude - Höhle 1

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#67]
- [x]  Bitte die Höhle hinzufügen, als Startgebäude.

- [x] Die Höhle dient gleichzeitig als kleines Lager für Nahrung und Baustoffe.
Insgesamt können so 25kg pro Ressourcen eingelagert werden.

- Pilz
- Fisch
- Knochen
- Holz
- Stein
(vorerst)

- [x]  im Radius 20 Kästchen um die Höhle darf gebaut werden

- [x]  das Lagerfeuer als Bauobjekt hinzufügen.

- [x]  5 Bewohner finden hier Platz

**Comment by flokicker** [comment]
erledigt
