### ISSUE TITLE
Jahreszeiten

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#78]
Sommerzeit: 
01.03 - 31.10.
Winterzeit:
01.11 - 28.02/29.02

Die Jahreszeiten brauchen noch nicht sichtbar sein. Falls möglich, kann es im Winter schneien.

Im Spielmenü, sollte man Schnee & Regen ein-/aus-blenden können. 
- Wetter einschalten/ausschalten

Die Jahreszeiten haben Einfluss auf die Ernte, sowie Nahrungsverbrauch. (  siehe dazugehörige Issues )

**Comment by flokicker** [comment]
Jahreszeit sichtbar über dem aktuellen Jahr
