### ISSUE TITLE
Fauna - Ente

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#79]
**Ente** 

- [x] Objekt anklickbar
- [x] Informationen abrufbar

**Ressourcen** 
- [x] Fleisch 
- [x] Knochen

- [x] Ressourcenabbau:
Produktion/Abbau - Sommer - Fleisch-Wild (Ente) pro Minute/pro 1 Arbeiter = 18
Produktion/Abbau - Winter - Fleisch-Wild (Ente) pro Minute/pro 1 Arbeiter = 18
Produktion/Abbau - Sommer - Knochen-Wild (Ente) pro Minute/pro 1 Arbeiter = 6
Produktion/Abbau - Winter - Knochen-Wild (Ente) pro Minute/pro 1 Arbeiter = 6

- [x]  Enten halten sich nur am Ufer auf.  (See, Weiher, Teich, Flus )
-> Maximale Entfernung vom Wasser: 10 Kästchen 

- [x]  Wildes umherlaufen von Enten innerhalb des Gebiets

- [x] Verbrauch innerhalb des Wohnraum-Bereichs ( Höhle )  1 Fleisch = 5 HP
- [x] Verbrauch außerhalb des Wohnraum-Bereichs ( Höhle )  1 Fleisch = 4 HP

**Comment by flokicker** [comment]
Sollen auch nur in Wasser-Nähe spawnen
