### ISSUE TITLE
Ernährungszyklus und Gebietserkundung

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#82]
- [x] Der Ernährungszyklus läuft innerhalb des Bereichs von dem Gebäude "Kornspeicher" automatisch.
Sprich, halten sich die Bewohner innerhalb des Bereichs auf, werden sie automatisch ernährt.
Sie greifen so also auf den Nahrungsvorrat zu.
Dafür müssen sie nicht zum Kornspeicher laufen, sondern es passiert automatisch im Hintergrund.
(Spielfluss-fördernd)

- [x] Der Bereich des Kornspeichers ist 35x35 Kästchen. 

- [x] Der Lebensbalken im Informations-Fenster des Bewohners ist **im Berich des Kornspeichers -> grün.** ( nicht der, über dem Kopf - ein extra Lebensbalken im Informations-Fenster )

- [x] Der Lebensbalken im Informations-Fenster des Bewohners ist **außerhalb des Bereichs des Kornspeichers -> orange.**

Begibt sich ein Bewohner außerhalb des Bereichs, hat er eine bestimmte zeit, die ihm bleibt um die Gegend zu erkunden.
Im Inventar ist es dem Spieler ermöglicht, Ressourcen in seinen "Nahrungs"-Beutel zu packen, dort kann er einen Pionier, auf die Reise schicken und befehlen, das Land zu erkunden. (Diese Eigenschaft des Pioniers, noch nicht hinzufügen - erst in 1.1/1.2 - Konzept dafür ist noch nicht ganz fertig, dient aber schon mal für die Information.)

- [x] Außerhalb des Bereichs verbraucht der Bewohner so Lebenspunkte ( bzw Nahrung ) & hungert aus. 
Lebenspunkt, im folgenden LP genannt.

- [x] LP verbrauch:
Sommer = 1 LP = 6 Sekunden
Winter = 1 LP = 4 Sekunden

- [x] 1 Korn bringt 5 LP und so 30 Sekunden weitere Zeit, das Gebiet zu erforschen, oder seinen Bewohner heil nach hause zu bringen.

**Comment by flokicker** [comment]
Zwei balken: gesundheit (GP) und Nahrung (NP)
Diese nehmen werte zwischen 0 und 100 an
(0=leer, 100=voll)

Farbe: (mag grad nicht alles aufzählen, 
- GP: über 50 grün (gesund), unter 50 orange (schlecht)
- NP: ausserhalb versorgungsbereich des kornspeichers: orange,
 innerhalb versorgungsbereich kornspeicher: grün

Verbrauch:
- GP: wenn NP < 20, dann  0.5 GP abzug pro sekunde
- NP: falls person satt, verliere 0.2 NP pro sekunde. Falls person nicht mehr satt, verliere 1 NP pro sekunde. Im winter wird dieser faktor mit 1.5 multipliziert.
- wenn der bewohner sich im versorgungsradius befindet, nimmt er automatisch essen aus dem Kornspeicher wenn er nicht mehr satt ist.
- wenn er essen im Inventar hat, isst er immer zuerst das, bevor er auf den Kornspeicher zurückgreift

Essen:
- wenn der bewohner gegessen hat, ist er für eine bestimmte zeit satt und isst erst wieder wenn die satt-zeit abgelaufen ist
- beim essen wird dem bewohner sofort GP und NP hinzugefügt, je nach essens-ressource
- jede essen-ressourxe hat 3 eigenschaften:
> wie viel gp die person bekommt
> wieviel np die person bekommt
> wielange die person satt ist

**Comment by flokicker** [comment]
Korn ausserhalb verschoben in #83 

Ernährungszyklus eingebaut
