### ISSUE TITLE
Bugs und Fehler in Version 0.04

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#86]
Kann natürlich sein, das manche in Issues schon gelistet sind, sorry dann, zwecks doppelter Aufzählung.

- [x] Gebäudeinventar fehlt ( Beispielweise Lagerhaus/Kornspeicher ), aber auch Fischerplatz, wie viele Fische lagern und welche Knochen wurden schon be-/ver-arbeitet.

- [x]  Bäume wachsen zu schnell. bitte den Wachstum auf um 40% reduzieren.

- [x] mehrere Bewohner befehl: laufen ineinander - bitte ändern, das Bewohner nicht ineinander laufen können. / stehen.

- [x] Mamorstein bitte in "Fels" ändern.

- [ ] Dinge die außerhalb des Sichtbereichs eines Bewohners / Gebäudes sind, schwarz machen bzw im Nebel. ( hast du irgendwo schon erwähnt )

- [x] Inventar Bewohner. aktuell steht nur Nahrung = 0
Bitte ändern in 0/20 etc. Die Information, wie viel ein Bewohner tragen kann, fehlt.

- [ ] Raster: Die Stellen die nicht zu bebauen sind ( schon bebeaut, Fluss, Stein, Flora/Fauna ) rot markieren

- [x] Baum fällen noch möglich, auch ohne beruf.

- [x]  Wenn man Stein abbaut, wackelt der Stein. Aber der Stein ist kein Baum ( :D ) und wird so ja auch nicht gefällt ( :D ) bitte den Stein ohne animation darstellen.

- [x]  Steinzeit-Schmied: Bitte das Lagerfeuer ohne Drehspieß 

- [x] Lager: Die Baustoffe lagern zu schnell ein. Bitte genauso wie in einer Baustelle einlagern.

- [x]  Inventar der Bewohner: Das Inventar von Erwachsenen bleibt gleich und wächst nicht weiter. Max 10 bitte. ( soll später erforscht werden dass das inventar größer wird.

- [x]  Modelltausch: Korn und Schilf. Die Modelle tauschen.

**Comment by flokicker** [comment]
übrige Punkte sind in anderen Issues enthalten
