### ISSUE TITLE
Große Feuerstelle

### ISSUE THREAD

**Issue by Alter04** [flokicker/dorfbauprojekt#94]
**Neues Gebäude**: Große Feuerstelle

- [x]  Das Gebäude ist erst Sichtbar und baubar, nachdem man 15 Einwohner besitzt.

- [x] **Sammelort für untätige / neue Bewohner:**
Durch den Bau des Gebäudes, werden alle neu-rekrutierten / geborenen Bewohner, sich hier um das Feuer versammeln. Ebenso finden sich hier auch Bewohner ein, die länger als 15 Minuten keine Aufgabe mehr inne hatten.

- [x] Die untätigen Bewohner halten die große Feuerstelle am brennen. 

- [x] Das Feuer kann 50 Holz fassen. ( selbe Abbrenn-geschwindigkeit, wie bei der kleinen Feuerstelle aktuell )

- [x]  Die Feuerstelle kann nur 10 untätige Bewohner fassen, weitere Bewohner die untätig sind / geboren wurden, bleiben da stehen, wo sie zuletzt waren.
Um weitere Sammelorte zu bauen, benötigt man weitere Feuerstellen. 

- [x] Bewohner Anzahl 1-100 = 1 große Feuerstelle baubar
Bewohner Anzahl 101-200 = 2 große Feuerstelle baubar
Bewohner Anzahl 201-300 = 3 große Feuerstelle baubar
Bewohner Anzahl 301-400 = 4 große Feuerstelle baubar
Bewohner Anzahl 401-500 = 5 große Feuerstelle baubar

- [x] Modell kommt per Mail
Größe 3x4

**Comment by flokicker** [comment]
denke 15minuten ist für den anfang zu lange, habs mal auf 5minutne gesetzt
ist ganz einfach später anzupassen

**Comment by flokicker** [comment]
die kleine Feuerstelle kann bis zu 2 untätige Bewohner sammeln

**Comment by flokicker** [comment]
sollten die neugeborenen Bewohner nicht im Haus ihrer Eltern spawnen?

Und das mit den rekrutierten truppen hab ich mir so vorgestellt, dass ein Bewohner zum Kriegsplatz kommandiert wird, da dann 5min in der ausbildung ist und dann ist er ein Soldat
